x-veld:
  code:
    description: "removes all lines before and after given line numbers"
    topics: 
      - "NLP"
      - "preprocessing"
      - "ETL"

    inputs:
      - volume: /veld/input/
        environment: in_file
        file_type: "txt"
        contents: "raw text"

    outputs:
      - volume: /veld/output/
        environment: out_file
        file_type: "txt"
        contents: "raw text"

    settings:
      - environment: line_start
        description: "line number before which lines will be stripped away. E.g. line_start=50
          removes lines from 1-49"
        env_type: "int" 
      - environment: line_end
        description: "line number after which lines will be stripped away. E.g. line_end=100 removes
          lines from 101-end"
        env_type: "int" 

services:
  veld_preprocess_strip:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: /veld/code/preprocess_strip.sh
    environment:
      in_file: null
      out_file: null
      line_start: null
      line_end: null

